version: '3'

services:
  # cloud9
  cloud9:
    image: linuxserver/cloud9:version-1.29.2
    container_name: cloud9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - /var/code:/code
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 8000:8000
    restart: always

  # Git WebUI
  git-webui-stable:
    image: earlybrain/git-webui:v1.5.0-1.0.0
    container_name: git-webui-stable
    volumes:
      - /var/code:/workspace
#    ports:
#      - 8008:9000
    restart: always

  # nginx
  nginx:
    image: nginx:1.21.1
    container_name: nginx
    volumes:
      - /var/code/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/code/etc/nginx/ssl:/etc/nginx/ssl
    links:
      - cloud9
      - git-webui-stable
    ports:
      - "8000:8000"
      - "8008:8008"
    restart: always
